### ISSUE TITLE
Add `excludes` option to `unescape`

### ISSUE THREAD

**Issue by phenomnomnominal** [hyurl/safe-string-literal#1]
Right now it is pretty hard to do a two way transform involving `excludes`. It would be great if the `unescape` function could also exclude some characters, e.g.:

```
export declare function escape(str: string, excludes?: string | string[]): string;
export declare function unescape(str: string, excludes?: string | string[]): string;
```

Happy to make a PR if you are interested.

**Comment by hyurl** [comment]
I'm not sure that is actually useful, the `excludes` for the `escape` function is meant to allow it not to escape some characters, that means keeping as-is, but for the `unescape` function, whether or not the `excludes` option was provided when escaping, the out string will not affect the result from the `unescape` function.

For example, `escape("abc'def", "'")` will output `abc'def` as-is, but either for `unescape("abc'def")` or `unescape("abc\\'def")`, the result will be the same.

**Comment by phenomnomnominal** [comment]
Sure, I get that! Currently I have `"\\'\\n"`, there's no easy way for me to end up with `\\'\n`. If that's intentional, that's all good, I'll just have to do it another way 😊
